local:
  directory:
    application: './' 

  debug: False


staging:
  directory:
    application: '/home/debian/covid-app/staging' 


production:
  directory:
    application: '/home/debian/covid-app/production' 

  host: '0.0.0.0'
  port: 8080
  