local:
  directory:
    application: './' 

  debug: True


staging:
  directory:
    application: '/home/debian/covid-app-staging' 


production:
  directory:
    application: '/home/debian/covid-app' 

  port: 80

